trigger:
  branches:
    include:
      - '*'

pool:
  Name: Pool-10

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build '
    steps:
    # Étape de construction du microservice 1
    - script: |
        echo 'Building and pushing Docker image for Microservice 1...'
        docker build -t francisntahimpera/alpine:latest -f src/makeline-service/Dockerfile .
        docker push francisntahimpera/alpine:latest
      displayName: 'Build and Push Microservice 1 Docker Image'

