name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBE_NAMESPACE: "default"
      DEPLOYMENT_FILE: "aks-store-quickstart.yaml"  
      
      

    steps:
     - name: Log in to Azure
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: Set up kubectl
       run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }}
  
     - name: Log in to Azure Container Registry
       run: az acr login --name ${{ env.REGISTRY_NAME }} --username ${{ env.REGISTRY_USERNAME }} --password ${{ env.REGISTRY_PASSWORD }}

     - name: Deploy to AKS
       run: |
          kubectl apply -f ${{ env.DEPLOYMENT_FILE }} -n ${{ env.KUBE_NAMESPACE }} --validate=false
