name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBE_NAMESPACE: "default"
      DEPLOYMENT_FILE: "aks-store-quickstart.yaml"  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AKS
      run: |
        kubectl apply -f ${{ env.DEPLOYMENT_FILE }} -n ${{ env.KUBE_NAMESPACE }} --validate=false
