etname: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        # RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
#      CLUSTER_NAME: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
  #    REGISTRY_NAME: ${{ secrets.ACR_NAME }}
#     REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
 #     REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      KUBE_NAMESPACE: "default"
      DEPLOYMENT_FILE: "/aks-store-quickstart.yaml"  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ secrets.ACR_NAME }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}

    - name: Set up kubectl
      run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}


    - name: Deploy to AKS
      run: |
        kubectl apply -f ${{ env.DEPLOYMENT_FILE }} -n ${{ env.KUBE_NAMESPACE }}
