name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBE_NAMESPACE: "default"
      DEPLOYMENT_FILE: "aks-store-all-in-one.yaml"  

 steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull Docker image
      run: docker pull ghcr.io/your-username/your-repo:your-tag
   

    - name: Deploy to AKS
      run: |
        kubectl apply -f ${{ env.DEPLOYMENT_FILE }} -n ${{ env.KUBE_NAMESPACE }} --validate=false
