name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
      REGISTRY_NAME: ${{ secrets.ACR_NAME }}
      REGISTRY_USERNAME: ${{ secrets.ACR_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      KUBE_NAMESPACE: "your-namespace"
      DEPLOYMENT_FILE: "path/to/your/deployment.yaml"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }}

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ env.REGISTRY_NAME }} --username ${{ env.REGISTRY_USERNAME }} --password ${{ env.REGISTRY_PASSWORD }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f ${{ env.DEPLOYMENT_FILE }} -n ${{ env.KUBE_NAMESPACE }}
